# Generated by Django 6.0.4 on 2026-04-27 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_name", models.CharField(max_length=30)),
                ("source", models.CharField(max_length=30)),
                ("dest", models.CharField(max_length=30)),
                ("nos", models.PositiveIntegerField()),
                ("rem", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("travel_time_hrs", models.FloatField(blank=True, null=True)),
                ("source_lat", models.FloatField(blank=True, null=True)),
                ("source_lon", models.FloatField(blank=True, null=True)),
                ("dest_lat", models.FloatField(blank=True, null=True)),
                ("dest_lon", models.FloatField(blank=True, null=True)),
                ("route_nodes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_name", models.CharField(max_length=30)),
                ("source", models.CharField(max_length=30)),
                ("dest", models.CharField(max_length=30)),
                ("nos", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("B", "Booked"), ("C", "Cancelled")],
                        default="B",
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="api.bus",
                    ),
                ),
            ],
        ),
    ]
