# Generated by Django 6.0.4 on 2026-04-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="busid",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="nos",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="userid",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="bus",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="nos",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="bus",
            name="rem",
            field=models.PositiveIntegerField(),
        ),
    ]
