# Generated by Django 6.0.4 on 2026-04-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_book_busid_alter_book_id_alter_book_nos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="dest_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="dest_lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="distance_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="source_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="source_lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="travel_time_hrs",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
