# Generated by Django 6.0.4 on 2026-04-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_bus_dest_lat_bus_dest_lon_bus_distance_km_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="route_nodes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
